### ISSUE TITLE
Designing WireFrame

### ISSUE THREAD

**Issue by yusungsamuel** [NVK2016/ProjectTwo#2]
Wire Frame for:

- Login Screen
- Create User Profile
- Activities DashBoard
      - Join activity
- Creating New Activities

**Comment by NVK2016** [comment]
1. Shayan - Created the wireframes for login , sign up & welcome page 
2. Namita- Create the wireframes for User Dashboard & View All members
3. the Screenshots all the wireframes are uploaded in the Project Doc
